version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/code"
      - '/code/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true